package com.kerby.example.database.repositories;

import com.kerby.example.database.models.PackageEntity;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

/**
 * A simple use of Spring Boot JPA to get CRUD access to an embedded H2 database to keep track of Packages.
 * An embedded H2 implementation is auto-generated by Spring.
 *
 * Due to Spring IoC this is really a DAO service
 */
@Repository
public interface PackageRepository extends CrudRepository<PackageEntity, Integer> {}

